import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    schema: 'src/schema.ts',
    config: 'src/config.ts',
    context: 'src/context.ts',
    services: 'src/services.ts',
    utils: 'src/utils.ts',
    logger: 'src/logger.ts',
    middleware: 'src/middleware.ts',
  },
  format: ['esm', 'cjs'],
  target: 'node18',
  outDir: 'dist',
  clean: false,
  dts: true,
  deps: {
    alwaysBundle: ['uuid', 'axios-retry'],
    neverBundle: [
      '@ajgifford/keepwatching-types',
      'axios',
      'cron-parser',
      'dotenv',
      'express',
      'firebase-admin',
      'ioredis',
      'mysql2',
      'node-cache',
      'node-cron',
      'nodemailer',
      'socket.io',
      'streaming-availability',
      'winston',
      'winston-daily-rotate-file',
      'zod',
      'knex',
    ],
  },
});
